# Generated by Django 5.1.6 on 2025-04-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_encryptedpaper_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedpaper',
            name='uploaded_by',
        ),
    ]
