# Generated by Django 5.1.6 on 2025-04-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_keyrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyRequest',
        ),
    ]
